import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {activeRoutineOccurrence,addSharedRoutine,alarmStateFor,applyDefaultKeyMappings,checklistComplete,dateKey,decodeRoutineShare,decodeSharePayload,delayAlarm,encodeRoutineShare,encodeSharePayload,formatDuration,freshRuntime,phaseContext,rememberAlarmState,routineFingerprint,runtimeKeyFor,startExclusiveRuntime,timestampFor,timestampForPhase,timestampForRoutineFinish,validConfig,validateRoutineSchedule,initialData,nextScheduledOccurrence} from '../routine-core.js';
test('countdown and lateness use timestamps',()=>{assert.equal(formatDuration(600000),'10:00');assert.equal(formatDuration(-1000),'00:01')});
test('scheduled time is independent from three delays',()=>{const now=new Date(2026,0,1,6,25).getTime(),scheduled=timestampFor('06:30',new Date(now));let alarm=scheduled;alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);assert.equal(scheduled,timestampFor('06:30',new Date(now)));assert.equal(alarm,timestampFor('06:33',new Date(now)))});
test('phase timestamps follow the routine date across midnight',()=>{const phases=[{time:'23:30'},{time:'23:45'},{time:'00:15'},{time:'06:00'}];assert.equal(timestampForPhase(phases,1,'2026-08-29'),new Date(2026,7,29,23,45).getTime());assert.equal(timestampForPhase(phases,2,'2026-08-29'),new Date(2026,7,30,0,15).getTime());assert.equal(timestampForPhase(phases,3,'2026-08-29'),new Date(2026,7,30,6,0).getTime())});
test('due alarm delays from now then accumulates',()=>{const now=100000;let alarm=delayAlarm(90000,now,true);assert.equal(alarm,160000);alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);assert.equal(alarm,280000)});
test('local date separates runtime days',()=>{assert.notEqual(dateKey(new Date(2026,0,1)),dateKey(new Date(2026,0,2)))});
test('a completed routine is stored only under its local calendar date',()=>{const routineId='morning',yesterday='2026-08-28',today='2026-08-29',completed={...freshRuntime(routineId,yesterday),started:true,phaseIndex:5,queued:true},stored={[runtimeKeyFor(routineId,yesterday)]:completed};assert.equal(stored[runtimeKeyFor(routineId,yesterday)].date,yesterday);assert.equal(stored[runtimeKeyFor(routineId,yesterday)].phaseIndex,5);assert.equal(stored[runtimeKeyFor(routineId,today)],undefined);const todayRuntime=stored[runtimeKeyFor(routineId,today)]=freshRuntime(routineId,today);assert.equal(todayRuntime.phaseIndex,-1);assert.equal(todayRuntime.started,false)});
test('default controls use P, Enter, and Space and migrate legacy defaults',()=>{const fresh=initialData();assert.deepEqual({previous:fresh.keys.previous,next:fresh.keys.next,delay:fresh.keys.delay},{previous:'KeyP',next:'Enter',delay:'Space'});const legacy={keys:{previous:'KeyP',next:'KeyN',delay:'KeyS'}};applyDefaultKeyMappings(legacy);assert.deepEqual(legacy.keys,{previous:'KeyP',next:'Enter',delay:'Space'});const customized={keys:{previous:'ArrowLeft',next:'ArrowRight',delay:'KeyD'}};applyDefaultKeyMappings(customized);assert.deepEqual(customized.keys,{previous:'ArrowLeft',next:'ArrowRight',delay:'KeyD'})});
test('backup validation permits an intentionally empty routine list',()=>{assert.equal(validConfig(initialData()),true);assert.equal(validConfig({schemaVersion:1,routines:[]}),true);assert.equal(validConfig({schemaVersion:99,routines:[]}),false)});
test('a fresh run targets the first phase so a late first alarm can sound',()=>{const phases=[{time:'14:30',name:'Get up'},{time:'14:45',name:'Breakfast'},{time:'15:00',name:'Leave'}],rt=freshRuntime('routine','2026-08-28');assert.equal(rt.phaseIndex,-1);assert.equal(phaseContext(phases,rt.phaseIndex).current,null);assert.equal(phaseContext(phases,rt.phaseIndex).next.name,'Get up');rt.phaseIndex++;assert.equal(phaseContext(phases,rt.phaseIndex).current.name,'Get up');assert.equal(phaseContext(phases,rt.phaseIndex).next.name,'Breakfast');rt.phaseIndex=phases.length;assert.equal(phaseContext(phases,rt.phaseIndex).current,null);rt.phaseIndex--;assert.equal(phaseContext(phases,rt.phaseIndex).current.name,'Leave')});
test('alarm delay is retained when navigating away and back',()=>{const rt=freshRuntime('routine'),first={id:'first'},second={id:'second'};rememberAlarmState(rt,first,123456,false);rememberAlarmState(rt,second,789000,true);assert.deepEqual(alarmStateFor(rt,first),{effectiveAlarm:123456,silenced:false});assert.deepEqual(alarmStateFor(rt,second),{effectiveAlarm:789000,silenced:true})});
test('share payload round trips unicode safely',()=>{const payload={routine:{name:'Café ☀️',phases:[{name:'Brush teeth'}]}};assert.deepEqual(decodeSharePayload(encodeSharePayload(payload)),payload)});
test('routine share links use the compact format and preserve routine settings',()=>{const routine=initialData().routines[0],encoded=encodeRoutineShare(routine),legacy=encodeSharePayload({schemaVersion:1,routine});const decoded=decodeRoutineShare(encoded).routine;assert.ok(encoded.length<legacy.length);assert.equal(routineFingerprint(decoded),routineFingerprint(routine));assert.ok(validConfig({schemaVersion:1,routines:[decoded]}))});
test('routine fingerprints ignore generated ids but detect meaningful edits',()=>{const routine=initialData().routines[0],copy=structuredClone(routine);copy.id='other';copy.phases.forEach((phase,index)=>phase.id=`phase-${index}`);assert.equal(routineFingerprint(copy),routineFingerprint(routine));copy.phases[0].name='Changed';assert.notEqual(routineFingerprint(copy),routineFingerprint(routine))});
test('a share link imports when a phase time differs from the local routine',()=>{const config=initialData(),shared=structuredClone(config.routines[0]);config.routines[0].phases[0].time='09:45';const result=addSharedRoutine(config,shared);assert.equal(result.imported,true);assert.equal(config.routines.length,2);assert.equal(result.routine.phases[0].time,'06:15');assert.equal(config.activeRoutineId,result.routine.id)});
test('a share link does not import a byte-for-byte equivalent routine twice',()=>{const config=initialData(),shared=structuredClone(config.routines[0]),result=addSharedRoutine(config,shared);assert.equal(result.imported,false);assert.equal(config.routines.length,1)});
test('app supports deleting the final routine and renders empty states',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/if\(t\.id==='deleteRoutine'&&confirm/);assert.match(app,/data\.routines\[0\]\?\.id\|\|null/);assert.match(app,/if\(!active\(\)\)return \$\('#run'\)/);assert.match(app,/if\(!r\)return \$\('#setup'\)/)});
test('routine editor time controls stay within their grid bounds',()=>{const css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(css,/grid-template-columns:minmax\(0,9\.5rem\) minmax\(0,1fr\) auto/);assert.match(css,/\.phase>input\[type=time\]\{[^}]*width:100%[^}]*min-width:0[^}]*max-width:100%/)});
test('configured checklist blocks until every item is checked',()=>{const phase={checklist:['Shoes','Bag']};assert.equal(checklistComplete(phase,[]),false);assert.equal(checklistComplete(phase,[true,false]),false);assert.equal(checklistComplete(phase,[true,true]),true);assert.equal(checklistComplete({checklist:[]},[]),true)});
test('new configuration supports independent routine runtimes',()=>{const config=initialData();assert.deepEqual(config.runtimes,{});const first=freshRuntime('first','2026-08-28'),second=freshRuntime('second','2026-08-28');const runtimes={[`${first.date}:${first.routineId}`]:first,[`${second.date}:${second.routineId}`]:second};first.phaseIndex=2;assert.equal(runtimes['2026-08-28:first'].phaseIndex,2);assert.equal(runtimes['2026-08-28:second'].phaseIndex,-1)});
test('app shell exposes reset in the simplified top bar and prevents page scrolling',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(html,/<header><nav><button id="reset"[^>]*>Reset today<\/button>/);assert.doesNotMatch(html,/fullscreen|class="brand"|data-view="run"/);assert.match(css,/html,body\{[^}]*overflow:hidden/);assert.match(css,/#run\{overflow:hidden/)})
test('active alarm stays compact inside the phase heading',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/class="heading-status"[\s\S]*<div class="alarm-alert" role="alert">/);assert.doesNotMatch(app,/class="alarm-banner"/);assert.match(css,/\.alarm-alert\{[^}]*display:flex[^}]*flex:none[^}]*white-space:nowrap/)})
test('starting a routine stops and resets every other routine today',()=>{const runtimes={'2026-08-28:morning':{...freshRuntime('morning','2026-08-28'),started:true,phaseIndex:2},'2026-08-28:bedtime':{...freshRuntime('bedtime','2026-08-28'),phaseIndex:1},'2026-08-27:morning':freshRuntime('morning','2026-08-27')};const active=startExclusiveRuntime(runtimes,'bedtime','2026-08-28');assert.equal(active.started,true);assert.equal(active.phaseIndex,1);assert.equal(runtimes['2026-08-28:morning'],undefined);assert.ok(runtimes['2026-08-27:morning'])});
test('starting a fresh routine immediately enters its first phase',()=>{const runtimes={};const active=startExclusiveRuntime(runtimes,'morning','2026-08-28');assert.equal(active.started,true);assert.equal(active.phaseIndex,0)});
test('run mode uses concise phase controls without an extra ready-to-begin step',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.doesNotMatch(app,/BEGIN FIRST PHASE|current\?\.name\|\|'Ready to begin'|Switch routine|Current phase<\/div>/);assert.match(app,/>PREVIOUS <small>\(P\)<\/small>/);assert.match(app,/\?'COMPLETE':'NEXT'/);assert.match(css,/#run \.actions\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/)});
test('run mode labels the next phase by its start time and cannot go before the first phase',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/'Next phase starts at'/);assert.doesNotMatch(app,/'Up next'\} · \$\{timeLabel\(next\.time\)\}/);assert.match(app,/id="previous" \$\{rt\.phaseIndex===0\?'disabled title="This is the first phase"'/);assert.match(app,/function previous\(\)\{const \{rt,next\}=nextInfo\(\);if\(rt\.phaseIndex<=0\)return/)});
test('run clock updates do not replace buttons during a tap',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/function refreshRunClock\(\)/);assert.match(app,/if\(view==='run'\)refreshRunClock\(\)/);assert.doesNotMatch(app,/setInterval\([^\n]*renderRun\(\)/);assert.match(css,/touch-action:manipulation/);assert.match(css,/@media\(hover:hover\) and \(pointer:fine\)\{button:hover/)});
test('run mode gives the checklist one full card and stacks phase times left of the countdown',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/class="hero current-phase"[\s\S]*\$\{currentContent\}<\/article><\/div>/);assert.match(app,/Current phase checklist/);assert.match(app,/class="countdown-row"[\s\S]*class="phase-times"[\s\S]*Scheduled start[\s\S]*Next phase starts at/);assert.doesNotMatch(app,/class="hero phase-progress"/);assert.match(css,/#run \.hero\{[^}]*overflow:auto/);assert.match(css,/#run \.countdown-row\{display:grid;grid-template-columns:minmax\(150px,25%\) minmax\(0,1fr\)/);assert.match(css,/#run \.countdown\{[^}]*container-type:inline-size/);assert.match(css,/#run \.timer\{font-size:clamp\(2rem,min\(11vh,16cqi\),8rem\)/);assert.match(css,/#run \.run-checklist label\{[^}]*font-size:clamp\(1rem,2\.5vmin,1\.5rem\)/);assert.match(app,/pointerdown',armAudio,\{once:true\}/);assert.doesNotMatch(app,/Silence alarm|Alarm sound on|id="audio"/)});
test('routine editor stays focused on one routine and has mobile card styling',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/class="editor-back" data-view="dashboard"/);assert.doesNotMatch(app,/class="routine-tabs"/);assert.match(app,/QR code preview/);assert.match(css,/@media\(max-width:600px\)[^{]*\{#setup \.panel/);assert.match(css,/#setup \.phase\{display:grid;grid-template-columns:1fr/)});
test('tablet layout includes overflow and older browser fallbacks',()=>{const css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(css,/@media \(min-width:701px\) and \(max-width:1100px\)/);assert.match(css,/#run\{overflow-y:auto/);assert.match(css,/@supports not \(overflow-wrap:anywhere\)/)});
test('completion confirmation queues the next scheduled run and keeps reset secondary',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/class="skip-today" id="markCompleteToday">Mark complete today/);assert.match(app,/id="acknowledgeStart">DISMISS ALARM & START ROUTINE/);assert.match(app,/markCompleteToday'\)\$\('#completeTodayDialog'\)\.showModal/);assert.match(app,/confirmMarkCompleteToday'[\s\S]*markCompleteToday\(\)/);assert.match(css,/\.queue-actions \.skip-today\{[^}]*min-height:44px[^}]*margin-top:/);assert.match(app,/class="primary complete-confirm" id="confirmCompleteToday"/);assert.match(app,/rt\.queued&&upcoming\)return renderScheduledStart\(upcoming,true\)/);assert.match(app,/Today is complete\. Your next scheduled routine is queued\./);assert.match(app,/class="secondary" data-reset-today>RESET TODAY/);assert.match(css,/\.complete-actions \.complete-confirm\{[^}]*min-height:100px/);assert.match(css,/\.complete-secondary \[data-reset-today\]\{[^}]*background:transparent/)});
test('completing the final phase immediately marks today complete and queues the next run',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/rt\.phaseIndex\+\+;if\(rt\.phaseIndex>=ps\.length\)rt\.queued=true;restoreAlarm/)});
test('a started routine is complete only after advancing beyond every phase',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/if\(rt\.phaseIndex>=ps\.length\)\{/);assert.doesNotMatch(app,/if\(!current\)return[^;]*routine-complete/)});
test('start button creates a fresh run anchored to its scheduled date',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/function startActiveRoutine\(\)\{const occurrence=scheduledStart\(\);delete data\.runtimes\[runtimeKey\(active\(\)\.id\)\]/);assert.match(app,/rt\.scheduledDate=occurrence\?\.date\|\|rt\.date/);assert.match(app,/timestampForPhase\(ps,rt\.phaseIndex\+1,rt\.scheduledDate\|\|rt\.date\)/);assert.match(app,/if\(t\.id==='start'\)\{if\(startActiveRoutine\(\)\)renderRun\(\)\}/)});

test('weekday schedule chooses the earliest enabled first phase after now',()=>{const monday=new Date(2026,7,31,6,0),routines=[{id:'later',days:[1],phases:[{time:'08:00',enabled:true}]},{id:'first',days:[1],phases:[{time:'07:00',enabled:true}]}];assert.deepEqual(nextScheduledOccurrence(routines,monday),{routineId:'first',date:'2026-08-31',scheduledAt:new Date(2026,7,31,7,0).getTime()})});
test('weekday schedule skips unchecked days and disabled first phases',()=>{const mondayAfterStart=new Date(2026,7,31,9,0),routines=[{id:'weekdays',days:[1,2,3,4,5],phases:[{time:'07:00',enabled:true}]},{id:'manual',days:[],phases:[{time:'10:00',enabled:true}]},{id:'disabled',days:[1],phases:[{time:'10:00',enabled:false}]}];const next=nextScheduledOccurrence(routines,mondayAfterStart);assert.equal(next.routineId,'weekdays');assert.equal(next.date,'2026-09-01')});
test('active routine alarm works across views and requires acknowledgement',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/addEventListener\('change',[\s\S]*dataset\.day/);assert.match(app,/function checkBackgroundAlarms\(\)[\s\S]*show\('run'\)/);assert.match(app,/function acknowledgeScheduledStart\(\)/);assert.match(app,/acknowledgment required/)})
test('scheduled alarms resume audio and survive reopening the active routine',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/async function playActiveAlarm\(sound\)[\s\S]*await audio\.resume\(\)[\s\S]*repeatAlarmSound/);assert.match(app,/function startScheduledAlarm\(\)[^\n]*playActiveAlarm\(phases\(\)\[0\]\?\.sound\)/);assert.match(app,/if\(data\.activeRoutineId!==t\.dataset\.viewRoutine\)dismissAlarm\(\)/);assert.doesNotMatch(app,/if\(t\.dataset\.viewRoutine\)\{dismissAlarm\(\)/)})
test('share links clear stale progress so the selected routine initializes and alarms normally',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/addSharedRoutine\(stored,payload\.routine\)[\s\S]*delete stored\.runtimes\[runtimeKeyFor\(result\.routine\.id\)\]/)});
test('low-power display uses the full duration countdown instead of total minutes',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/function idleSummary\(\)[\s\S]*in \$\{formatDuration\(remaining\)\}/);assert.doesNotMatch(app,/Math\.ceil\(\(transitionTimestamp[\s\S]*\/60000\)/)});

test('completion advances a daily active routine to tomorrow instead of leaving today overdue',()=>{const monday=new Date(2026,7,31,9,0),routine={id:'morning',days:[0,1,2,3,4,5,6],phases:[{time:'06:00',enabled:true}]};assert.deepEqual(activeRoutineOccurrence(routine,monday,true),{routineId:'morning',date:'2026-09-01',scheduledAt:new Date(2026,8,1,6,0).getTime()});assert.equal(activeRoutineOccurrence(routine,monday,false).scheduledAt,new Date(2026,7,31,6,0).getTime())});

test('routine finish time follows the final phase and supports overnight routines',()=>{const routine={finishTime:'00:30',phases:[{time:'23:30',enabled:true},{time:'00:10',enabled:true}]};assert.equal(timestampForRoutineFinish(routine,'2026-08-29'),new Date(2026,7,30,0,30).getTime())});
test('routine schedule validation requires a completion time and chronological phases',()=>{assert.equal(validateRoutineSchedule({finishTime:'',phases:[]}), 'Choose a routine complete time.');assert.match(validateRoutineSchedule({finishTime:'09:00',phases:[{time:'08:30',name:'First'},{time:'08:00',name:'Second'}]}),/previous phase/);assert.match(validateRoutineSchedule({finishTime:'08:15',phases:[{time:'08:30',name:'Leave'}]}),/cannot be earlier/);assert.equal(validateRoutineSchedule({finishTime:'09:00',phases:[{time:'08:00'},{time:'08:30'}]}),'')});
test('editor places required completion time after phases and offers a QR preview',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.ok(app.indexOf('id="finishTime"')>app.indexOf('id="phaseList"'));assert.match(app,/id="saveRoutine"/);assert.match(app,/validateRoutineSchedule\(editorDraft\)/);assert.match(app,/id="qrRoutine">QR code preview/);assert.match(html,/id="qrDialog"/)});
test('routine finish time is shared and shown in the editor',()=>{const routine=initialData().routines[0],decoded=decodeRoutineShare(encodeRoutineShare(routine)).routine,app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.equal(decoded.finishTime,routine.finishTime);assert.match(app,/id=\"finishTime\" type=\"time\"/);assert.match(app,/The final phase counts down/);assert.match(app,/timestampForRoutineFinish/)});

test('low-power display is configurable, moves, and wakes for interaction or alarms',()=>{const config=initialData(),app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.equal(config.preferences.idleMinutes,2);assert.equal(config.preferences.keepAwakeDuringAlarm,true);assert.match(html,/id="idleDisplay"/);assert.match(app,/\[1,2,5,10\]/);assert.match(app,/positions=\[\[50,20\]/);assert.match(app,/\['pointerdown','touchstart','click'\]/);assert.match(app,/function startAlarm\(\)\{alarmSounding=true;wakeFullDisplay\(\)/);assert.match(app,/alarmSounding&&data\.preferences\.keepAwakeDuringAlarm/);assert.match(css,/#idleDisplay\{[^}]*position:fixed/)});
