import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {alarmStateFor,checklistComplete,dateKey,decodeSharePayload,delayAlarm,encodeSharePayload,formatDuration,freshRuntime,phaseContext,rememberAlarmState,startExclusiveRuntime,timestampFor,validConfig,initialData} from '../routine-core.js';
test('countdown and lateness use timestamps',()=>{assert.equal(formatDuration(600000),'10:00');assert.equal(formatDuration(-1000),'00:01')});
test('scheduled time is independent from three delays',()=>{const now=new Date(2026,0,1,6,25).getTime(),scheduled=timestampFor('06:30',new Date(now));let alarm=scheduled;alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);assert.equal(scheduled,timestampFor('06:30',new Date(now)));assert.equal(alarm,timestampFor('06:33',new Date(now)))});
test('due alarm delays from now then accumulates',()=>{const now=100000;let alarm=delayAlarm(90000,now,true);assert.equal(alarm,160000);alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);assert.equal(alarm,280000)});
test('local date separates runtime days',()=>{assert.notEqual(dateKey(new Date(2026,0,1)),dateKey(new Date(2026,0,2)))});
test('backup validation',()=>{assert.equal(validConfig(initialData()),true);assert.equal(validConfig({schemaVersion:99,routines:[]}),false)});
test('a fresh run targets the first scheduled phase',()=>{const phases=[{time:'14:30'},{time:'14:45'},{time:'15:00'}],rt=freshRuntime('routine','2026-08-28');assert.equal(rt.phaseIndex,-1);assert.equal(phaseContext(phases,rt.phaseIndex).next.time,'14:30');rt.phaseIndex++;assert.equal(phaseContext(phases,rt.phaseIndex).next.time,'14:45');rt.phaseIndex++;assert.equal(phaseContext(phases,rt.phaseIndex).next.time,'15:00')});
test('alarm delay is retained when navigating away and back',()=>{const rt=freshRuntime('routine'),first={id:'first'},second={id:'second'};rememberAlarmState(rt,first,123456,false);rememberAlarmState(rt,second,789000,true);assert.deepEqual(alarmStateFor(rt,first),{effectiveAlarm:123456,silenced:false});assert.deepEqual(alarmStateFor(rt,second),{effectiveAlarm:789000,silenced:true})});
test('share payload round trips unicode safely',()=>{const payload={routine:{name:'Café ☀️',phases:[{name:'Brush teeth'}]}};assert.deepEqual(decodeSharePayload(encodeSharePayload(payload)),payload)});
test('configured checklist blocks until every item is checked',()=>{const phase={checklist:['Shoes','Bag']};assert.equal(checklistComplete(phase,[]),false);assert.equal(checklistComplete(phase,[true,false]),false);assert.equal(checklistComplete(phase,[true,true]),true);assert.equal(checklistComplete({checklist:[]},[]),true)});
test('new configuration supports independent routine runtimes',()=>{const config=initialData();assert.deepEqual(config.runtimes,{});const first=freshRuntime('first','2026-08-28'),second=freshRuntime('second','2026-08-28');const runtimes={[`${first.date}:${first.routineId}`]:first,[`${second.date}:${second.routineId}`]:second};first.phaseIndex=2;assert.equal(runtimes['2026-08-28:first'].phaseIndex,2);assert.equal(runtimes['2026-08-28:second'].phaseIndex,-1)});
test('app shell exposes top-bar fullscreen and prevents page scrolling',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(html,/id="fullscreen"[^>]*>⛶ Go Fullscreen/);assert.match(css,/html,body\{[^}]*overflow:hidden/);assert.match(css,/#run\{overflow:hidden/)})
test('active alarm stays compact inside the routine context row',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/<div class="alarm-alert" role="alert">/);assert.doesNotMatch(app,/class="alarm-banner"/);assert.match(css,/\.alarm-alert\{[^}]*display:flex[^}]*flex:none[^}]*white-space:nowrap/)})
test('starting a routine stops and resets every other routine today',()=>{const runtimes={'2026-08-28:morning':{...freshRuntime('morning','2026-08-28'),started:true,phaseIndex:2},'2026-08-28:bedtime':{...freshRuntime('bedtime','2026-08-28'),phaseIndex:1},'2026-08-27:morning':freshRuntime('morning','2026-08-27')};const active=startExclusiveRuntime(runtimes,'bedtime','2026-08-28');assert.equal(active.started,true);assert.equal(active.phaseIndex,1);assert.equal(runtimes['2026-08-28:morning'],undefined);assert.ok(runtimes['2026-08-27:morning'])});
test('run mode keeps the checklist in the current phase card and arms sound by default',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/class="hero current-phase"[\s\S]*\$\{currentContent\}/);assert.match(app,/Current phase checklist/);assert.match(app,/class="next-description"/);assert.match(app,/pointerdown',armAudio,\{once:true\}/);assert.match(app,/Alarm sound on/)});
test('tablet layout includes overflow and older browser fallbacks',()=>{const css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(css,/@media \(min-width:701px\) and \(max-width:1100px\)/);assert.match(css,/#run\{overflow-y:auto/);assert.match(css,/@supports not \(overflow-wrap:anywhere\)/)});
