import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {activeRoutineOccurrence,alarmStateFor,checklistComplete,dateKey,decodeSharePayload,delayAlarm,encodeSharePayload,formatDuration,freshRuntime,phaseContext,rememberAlarmState,startExclusiveRuntime,timestampFor,validConfig,initialData,nextScheduledOccurrence} from '../routine-core.js';
test('countdown and lateness use timestamps',()=>{assert.equal(formatDuration(600000),'10:00');assert.equal(formatDuration(-1000),'00:01')});
test('scheduled time is independent from three delays',()=>{const now=new Date(2026,0,1,6,25).getTime(),scheduled=timestampFor('06:30',new Date(now));let alarm=scheduled;alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);assert.equal(scheduled,timestampFor('06:30',new Date(now)));assert.equal(alarm,timestampFor('06:33',new Date(now)))});
test('due alarm delays from now then accumulates',()=>{const now=100000;let alarm=delayAlarm(90000,now,true);assert.equal(alarm,160000);alarm=delayAlarm(alarm,now,false);alarm=delayAlarm(alarm,now,false);assert.equal(alarm,280000)});
test('local date separates runtime days',()=>{assert.notEqual(dateKey(new Date(2026,0,1)),dateKey(new Date(2026,0,2)))});
test('backup validation',()=>{assert.equal(validConfig(initialData()),true);assert.equal(validConfig({schemaVersion:99,routines:[]}),false)});
test('a fresh run targets the first phase so a late first alarm can sound',()=>{const phases=[{time:'14:30',name:'Get up'},{time:'14:45',name:'Breakfast'},{time:'15:00',name:'Leave'}],rt=freshRuntime('routine','2026-08-28');assert.equal(rt.phaseIndex,-1);assert.equal(phaseContext(phases,rt.phaseIndex).current,null);assert.equal(phaseContext(phases,rt.phaseIndex).next.name,'Get up');rt.phaseIndex++;assert.equal(phaseContext(phases,rt.phaseIndex).current.name,'Get up');assert.equal(phaseContext(phases,rt.phaseIndex).next.name,'Breakfast');rt.phaseIndex=phases.length;assert.equal(phaseContext(phases,rt.phaseIndex).current,null);rt.phaseIndex--;assert.equal(phaseContext(phases,rt.phaseIndex).current.name,'Leave')});
test('alarm delay is retained when navigating away and back',()=>{const rt=freshRuntime('routine'),first={id:'first'},second={id:'second'};rememberAlarmState(rt,first,123456,false);rememberAlarmState(rt,second,789000,true);assert.deepEqual(alarmStateFor(rt,first),{effectiveAlarm:123456,silenced:false});assert.deepEqual(alarmStateFor(rt,second),{effectiveAlarm:789000,silenced:true})});
test('share payload round trips unicode safely',()=>{const payload={routine:{name:'Café ☀️',phases:[{name:'Brush teeth'}]}};assert.deepEqual(decodeSharePayload(encodeSharePayload(payload)),payload)});
test('configured checklist blocks until every item is checked',()=>{const phase={checklist:['Shoes','Bag']};assert.equal(checklistComplete(phase,[]),false);assert.equal(checklistComplete(phase,[true,false]),false);assert.equal(checklistComplete(phase,[true,true]),true);assert.equal(checklistComplete({checklist:[]},[]),true)});
test('new configuration supports independent routine runtimes',()=>{const config=initialData();assert.deepEqual(config.runtimes,{});const first=freshRuntime('first','2026-08-28'),second=freshRuntime('second','2026-08-28');const runtimes={[`${first.date}:${first.routineId}`]:first,[`${second.date}:${second.routineId}`]:second};first.phaseIndex=2;assert.equal(runtimes['2026-08-28:first'].phaseIndex,2);assert.equal(runtimes['2026-08-28:second'].phaseIndex,-1)});
test('app shell exposes reset in the simplified top bar and prevents page scrolling',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(html,/<header><nav><button id="reset"[^>]*>Reset today<\/button>/);assert.doesNotMatch(html,/fullscreen|class="brand"|data-view="run"/);assert.match(css,/html,body\{[^}]*overflow:hidden/);assert.match(css,/#run\{overflow:hidden/)})
test('active alarm stays compact inside the routine context row',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/<div class="alarm-alert" role="alert">/);assert.doesNotMatch(app,/class="alarm-banner"/);assert.match(css,/\.alarm-alert\{[^}]*display:flex[^}]*flex:none[^}]*white-space:nowrap/)})
test('starting a routine stops and resets every other routine today',()=>{const runtimes={'2026-08-28:morning':{...freshRuntime('morning','2026-08-28'),started:true,phaseIndex:2},'2026-08-28:bedtime':{...freshRuntime('bedtime','2026-08-28'),phaseIndex:1},'2026-08-27:morning':freshRuntime('morning','2026-08-27')};const active=startExclusiveRuntime(runtimes,'bedtime','2026-08-28');assert.equal(active.started,true);assert.equal(active.phaseIndex,1);assert.equal(runtimes['2026-08-28:morning'],undefined);assert.ok(runtimes['2026-08-27:morning'])});
test('starting a fresh routine immediately enters its first phase',()=>{const runtimes={};const active=startExclusiveRuntime(runtimes,'morning','2026-08-28');assert.equal(active.started,true);assert.equal(active.phaseIndex,0)});
test('run mode does not show an extra ready-to-begin step after start',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.doesNotMatch(app,/BEGIN FIRST PHASE|current\?\.name\|\|'Ready to begin'/);assert.match(app,/>NEXT PHASE <small>\(N\)<\/small>/)});
test('run mode gives the checklist one full card and keeps next phase compact',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/class="hero current-phase"[\s\S]*\$\{currentContent\}<\/article><\/div>/);assert.match(app,/Current phase checklist/);assert.match(app,/class="countdown-row"[\s\S]*class="next-indicator"/);assert.doesNotMatch(app,/class="hero phase-progress"/);assert.match(css,/#run \.hero\{[^}]*overflow:auto/);assert.match(app,/pointerdown',armAudio,\{once:true\}/);assert.doesNotMatch(app,/Silence alarm|Alarm sound on|id="audio"/)});
test('tablet layout includes overflow and older browser fallbacks',()=>{const css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(css,/@media \(min-width:701px\) and \(max-width:1100px\)/);assert.match(css,/#run\{overflow-y:auto/);assert.match(css,/@supports not \(overflow-wrap:anywhere\)/)});
test('completion confirmation queues the next scheduled run and keeps reset secondary',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8'),css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(app,/id="markCompleteToday">MARK COMPLETE TODAY/);assert.match(app,/id="acknowledgeStart">DISMISS ALARM & START ROUTINE/);assert.match(app,/class="primary complete-confirm" id="confirmCompleteToday"/);assert.match(app,/rt\.queued&&upcoming\)return renderScheduledStart\(upcoming,true\)/);assert.match(app,/Today is complete\. Your next scheduled routine is queued\./);assert.match(app,/class="secondary" data-reset-today>RESET TODAY/);assert.match(css,/\.complete-actions \.complete-confirm\{[^}]*min-height:100px/);assert.match(css,/\.complete-secondary \[data-reset-today\]\{[^}]*background:transparent/)});
test('a started routine is complete only after advancing beyond every phase',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/if\(rt\.phaseIndex>=ps\.length\)\{/);assert.doesNotMatch(app,/if\(!current\)return[^;]*routine-complete/)});
test('start button always creates a fresh run after resetting today',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/function startActiveRoutine\(\)\{delete data\.runtimes\[runtimeKey\(active\(\)\.id\)\];return switchAndStart\(active\(\)\.id\)\}/);assert.match(app,/if\(t\.id==='start'\)\{if\(startActiveRoutine\(\)\)renderRun\(\)\}/)});

test('weekday schedule chooses the earliest enabled first phase after now',()=>{const monday=new Date(2026,7,31,6,0),routines=[{id:'later',days:[1],phases:[{time:'08:00',enabled:true}]},{id:'first',days:[1],phases:[{time:'07:00',enabled:true}]}];assert.deepEqual(nextScheduledOccurrence(routines,monday),{routineId:'first',date:'2026-08-31',scheduledAt:new Date(2026,7,31,7,0).getTime()})});
test('weekday schedule skips unchecked days and disabled first phases',()=>{const mondayAfterStart=new Date(2026,7,31,9,0),routines=[{id:'weekdays',days:[1,2,3,4,5],phases:[{time:'07:00',enabled:true}]},{id:'manual',days:[],phases:[{time:'10:00',enabled:true}]},{id:'disabled',days:[1],phases:[{time:'10:00',enabled:false}]}];const next=nextScheduledOccurrence(routines,mondayAfterStart);assert.equal(next.routineId,'weekdays');assert.equal(next.date,'2026-09-01')});
test('active routine alarm works across views and requires acknowledgement',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(app,/addEventListener\('change',[\s\S]*dataset\.day/);assert.match(app,/function checkBackgroundAlarms\(\)[\s\S]*show\('run'\)/);assert.match(app,/function acknowledgeScheduledStart\(\)/);assert.match(app,/acknowledgment required/)})

test('completion advances a daily active routine to tomorrow instead of leaving today overdue',()=>{const monday=new Date(2026,7,31,9,0),routine={id:'morning',days:[0,1,2,3,4,5,6],phases:[{time:'06:00',enabled:true}]};assert.deepEqual(activeRoutineOccurrence(routine,monday,true),{routineId:'morning',date:'2026-09-01',scheduledAt:new Date(2026,8,1,6,0).getTime()});assert.equal(activeRoutineOccurrence(routine,monday,false).scheduledAt,new Date(2026,7,31,6,0).getTime())});
