import {STORAGE_KEY,dateKey,delayAlarm,formatDuration,initialData,timestampFor,uid,validConfig} from './routine-core.js';
let data=load(), view='run', now=Date.now(), alarmSounding=false, audio=null, wakeLock=null, editingRoutine=data.activeRoutineId;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return validConfig(x)?x:initialData()}catch{return initialData()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function active(){return data.routines.find(r=>r.id===data.activeRoutineId)||data.routines[0]}
function phases(){return active().phases.filter(p=>p.enabled)}
function ensureRuntime(){const today=dateKey();if(!data.runtime||data.runtime.date!==today||data.runtime.routineId!==active().id)data.runtime={date:today,routineId:active().id,phaseIndex:0,effectiveAlarm:null,silenced:false,started:false};save();return data.runtime}
function nextInfo(){const ps=phases(),rt=ensureRuntime(), current=ps[Math.min(rt.phaseIndex,ps.length-1)], next=ps[rt.phaseIndex+1];return{ps,rt,current,next}}
function timeLabel(time){const [h,m]=time.split(':');return new Date(2000,0,1,+h,+m).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function renderRun(){const {rt,current,next}=nextInfo();if(!current)return $('#run').innerHTML='<div class="panel"><h1>No enabled phases</h1><button data-view="setup">Configure routine</button></div>';
  if(!rt.started) return $('#run').innerHTML=`<div class="panel" style="text-align:center"><div class="eyebrow">Ready for</div><h1 class="current-name">${esc(active().name)}</h1><p>Start when you are ready. Today’s progress is saved on this device.</p><button class="primary" id="start" style="font-size:2rem;padding:1.2rem 3rem">START ROUTINE</button></div>`;
  if(!next)return $('#run').innerHTML=`<div class="hero" style="text-align:center"><div class="eyebrow">Routine complete</div><h1 class="current-name">${esc(current.name)}</h1><div class="timer">✓</div><button id="reset">RESET TODAY’S ROUTINE</button></div>`;
  const scheduled=timestampFor(next.time,new Date(now));if(rt.effectiveAlarm==null)rt.effectiveAlarm=scheduled;
  const delta=scheduled-now, late=delta<0; const delayed=rt.effectiveAlarm!==scheduled;
  $('#run').innerHTML=`${alarmSounding?'<div class="alarm-banner">🔔 TIME FOR THE NEXT PHASE</div>':''}<div class="run-grid"><article class="hero"><div class="eyebrow">Current</div><h1 class="current-name">${esc(current.name)}</h1><div class="instructions">${esc(current.description)||'Keep going—you’ve got this.'}</div></article><article class="hero"><div class="eyebrow">Next</div><h2 class="next-name">${esc(next.name)}</h2><div class="scheduled">Scheduled ${timeLabel(next.time)}</div></article></div><div class="timer ${late?'late':''}">${late?'+':''}${formatDuration(delta)}</div><div class="timer-label">${late?'LATE':'REMAINING'}</div><div class="delay-note">${delayed?`Alarm delayed until ${new Date(rt.effectiveAlarm).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:''}</div><div class="actions"><button class="delay" id="delay">+1 MIN ALARM <small>(S)</small></button><button class="advance" id="advance">NEXT PHASE <small>(N)</small></button></div><div class="minor-actions"><button id="silence">Silence alarm (D)</button><button id="audio">${audio?'✓ Alarm sound enabled':'Enable alarm sound'}</button><button id="fullscreen">Fullscreen</button><button id="reset">Reset today</button></div>`;
  if(next.alarm && now>=rt.effectiveAlarm && !rt.silenced && !alarmSounding)startAlarm();
}
function startAlarm(){alarmSounding=true;if(audio){const sound=nextInfo().next?.sound||data.preferences.sound;const play=()=>{if(!alarmSounding)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=sound==='gentle'?520:780;g.gain.value=data.preferences.volume*.25;o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.35);setTimeout(play,650)};play()}renderRun()}
function silence(){alarmSounding=false;ensureRuntime().silenced=true;save();renderRun()}
function delay(){const rt=ensureRuntime(), scheduled=nextInfo().next&&timestampFor(nextInfo().next.time,new Date(now));if(!scheduled)return;rt.effectiveAlarm=delayAlarm(rt.effectiveAlarm??scheduled,Date.now(),alarmSounding||Date.now()>=rt.effectiveAlarm);rt.silenced=false;alarmSounding=false;save();renderRun()}
function advance(){const rt=ensureRuntime();alarmSounding=false;rt.phaseIndex++;rt.effectiveAlarm=null;rt.silenced=false;save();renderRun()}
function renderSetup(){editingRoutine=data.routines.some(r=>r.id===editingRoutine)?editingRoutine:data.activeRoutineId;const r=data.routines.find(x=>x.id===editingRoutine);$('#setup').innerHTML=`<div class="panel"><div class="panel-head"><div><div class="eyebrow">Routine editor</div><h1>Your routines</h1></div><div class="toolbar"><button id="activate" class="primary">${r.id===data.activeRoutineId?'✓ Active routine':'Use this routine'}</button><button id="newRoutine">+ New</button><button id="duplicate">Duplicate</button><button class="danger" id="deleteRoutine">Delete</button></div></div><div class="routine-tabs">${data.routines.map(x=>`<button class="${x.id===r.id?'selected':''}" data-routine="${x.id}">${x.id===data.activeRoutineId?'● ':''}${esc(x.name)}</button>`).join('')}</div><label>Routine name<input id="routineName" type="text" value="${esc(r.name)}"></label><div class="days">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<label><input type="checkbox" data-day="${i}" ${r.days?.includes(i)?'checked':''}> ${d}</label>`).join('')}</div></div><div class="panel"><div class="panel-head"><h2>Phases</h2><button class="primary" id="addPhase">+ Add phase</button></div><p>Phases run in this order. Each time is the scheduled start of that phase.</p><div id="phaseList">${r.phases.map((p,i)=>`<div class="phase" data-phase="${p.id}"><input type="time" data-field="time" value="${p.time}"><div class="phase-fields"><input type="text" data-field="name" aria-label="Phase name" value="${esc(p.name)}"><textarea data-field="description" rows="2" placeholder="Optional instructions">${esc(p.description)}</textarea><label><input type="checkbox" data-field="alarm" ${p.alarm?'checked':''}> Sound alarm for this transition</label><label>Alarm sound <select data-field="sound"><option value="chime" ${p.sound==='chime'?'selected':''}>Bright chime</option><option value="gentle" ${p.sound==='gentle'?'selected':''}>Gentle chime</option></select></label><label><input type="checkbox" data-field="enabled" ${p.enabled?'checked':''}> Enabled</label></div><div class="phase-controls"><button data-move="-1" ${i===0?'disabled':''}>↑</button><button data-move="1" ${i===r.phases.length-1?'disabled':''}>↓</button><button class="danger" data-remove>×</button></div></div>`).join('')}</div></div>`}
function renderSettings(){const k=data.keys;$('#settings').innerHTML=`<h1>Settings</h1><div class="settings-grid"><section class="panel"><h2>Keyboard controls</h2><p>Click a mapping, then press the desired hardware button.</p>${['next','delay','silence'].map(x=>`<label>${x[0].toUpperCase()+x.slice(1)}<button class="keymap" data-map="${x}">${esc(k[x])}</button></label>`).join('')}<div class="key-capture" tabindex="0">Keyboard test<br><strong id="keyDebug">Press any key…</strong></div></section><section class="panel"><h2>Alarm</h2><label>Sound<select id="sound"><option value="chime" ${data.preferences.sound==='chime'?'selected':''}>Bright chime</option><option value="gentle" ${data.preferences.sound==='gentle'?'selected':''}>Gentle chime</option></select></label><label>Volume <input id="volume" type="range" min="0" max="1" step=".1" value="${data.preferences.volume}"></label><button id="audio">Enable / test sound</button></section></div><section class="panel"><h2>Backup & restore</h2><p>Export includes routines, preferences, mappings, and today’s state.</p><div class="toolbar"><button id="export">Export settings</button><button id="import">Import settings</button></div></section><section class="panel"><h2>Storage</h2><p>Everything stays in this browser under <code>${STORAGE_KEY}</code>. No account or network is used.</p></section>`}
function show(v){view=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('hidden',x.id!==v));if(v==='run'){renderRun();requestWake()}else if(v==='setup')renderSetup();else renderSettings()}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
async function enableAudio(){audio ||= new (window.AudioContext||window.webkitAudioContext)();await audio.resume();const o=audio.createOscillator();o.connect(audio.destination);o.start();o.stop(audio.currentTime+.08);toast('Alarm sound enabled');renderRun()}
async function requestWake(){try{if('wakeLock'in navigator&&!wakeLock)wakeLock=await navigator.wakeLock.request('screen')}catch{}}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view)return show(t.dataset.view);if(t.id==='start'){ensureRuntime().started=true;save();renderRun()}if(t.id==='delay')delay();if(t.id==='advance')advance();if(t.id==='silence')silence();if(t.id==='audio')enableAudio();if(t.id==='fullscreen')document.documentElement.requestFullscreen?.();if(t.id==='reset'&&confirm('Start today’s routine over?')){data.runtime=null;alarmSounding=false;save();renderRun()}if(t.dataset.routine){editingRoutine=t.dataset.routine;renderSetup()}if(t.id==='activate'){data.activeRoutineId=editingRoutine;data.runtime=null;alarmSounding=false;save();renderSetup();toast('Active routine changed')}if(t.id==='newRoutine'){const r={id:uid(),name:'New Routine',days:[],phases:[]};data.routines.push(r);editingRoutine=r.id;save();renderSetup()}if(t.id==='duplicate'){const source=data.routines.find(r=>r.id===editingRoutine),r=structuredClone(source);r.id=uid();r.name+=' Copy';r.phases.forEach(p=>p.id=uid());data.routines.push(r);editingRoutine=r.id;save();renderSetup()}if(t.id==='deleteRoutine'&&data.routines.length>1&&confirm('Delete this routine?')){data.routines=data.routines.filter(r=>r.id!==editingRoutine);editingRoutine=data.activeRoutineId=data.routines[0].id;data.runtime=null;save();renderSetup()}if(t.id==='addPhase'){data.routines.find(r=>r.id===editingRoutine).phases.push({id:uid(),time:'08:00',name:'New phase',description:'',alarm:true,enabled:true,sound:'chime'});save();renderSetup()}if(t.dataset.remove!==undefined){const r=data.routines.find(r=>r.id===editingRoutine);r.phases=r.phases.filter(p=>p.id!==t.closest('.phase').dataset.phase);save();renderSetup()}if(t.dataset.move){const r=data.routines.find(r=>r.id===editingRoutine),i=r.phases.findIndex(p=>p.id===t.closest('.phase').dataset.phase),j=i+Number(t.dataset.move);[r.phases[i],r.phases[j]]=[r.phases[j],r.phases[i]];save();renderSetup()}if(t.id==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`routine-beacon-${dateKey()}.json`;a.click();URL.revokeObjectURL(a.href)}if(t.id==='import')$('#importFile').click();if(t.classList.contains('keymap')){t.textContent='Press a key…';t.dataset.listening='true'}});
document.addEventListener('input',e=>{const r=data.routines.find(r=>r.id===editingRoutine);if(e.target.id==='routineName')r.name=e.target.value;if(e.target.dataset.day!==undefined){const d=+e.target.dataset.day;r.days=e.target.checked?[...new Set([...(r.days||[]),d])]:(r.days||[]).filter(x=>x!==d)}const row=e.target.closest('.phase');if(row){const p=r.phases.find(p=>p.id===row.dataset.phase),f=e.target.dataset.field;p[f]=e.target.type==='checkbox'?e.target.checked:e.target.value}if(e.target.id==='sound')data.preferences.sound=e.target.value;if(e.target.id==='volume')data.preferences.volume=+e.target.value;save()});
document.addEventListener('keydown',e=>{const listening=document.querySelector('[data-listening=true]');$('#keyDebug')&&($('#keyDebug').textContent=`key: ${e.key} · code: ${e.code}`);if(listening){e.preventDefault();data.keys[listening.dataset.map]=e.code;save();renderSettings();return}if(view!=='run'||e.repeat)return;if(e.code===data.keys.next){e.preventDefault();advance()}if(e.code===data.keys.delay){e.preventDefault();delay()}if(e.code===data.keys.silence){e.preventDefault();silence()}});
$('#importFile').addEventListener('change',async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!validConfig(x))throw Error();if(confirm('Replace all current settings with this backup?')){data=x;editingRoutine=data.activeRoutineId;alarmSounding=false;save();show('settings');toast('Backup restored')}}catch{alert('This is not a valid Routine Beacon backup.')}e.target.value=''});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&view==='run')requestWake()});
setInterval(()=>{now=Date.now();if(view==='run')renderRun()},250);window.addEventListener('beforeunload',save);document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>{}));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');show('run');
